### ISSUE TITLE
Good code...

### ISSUE THREAD

**Issue by RajisteB** [jakemeltzer333/Game-of-Thrones-for-Dummies#2]
No real issues at all, seems pretty straightforward from my view...
I like the way you made your insertion of your data into your API call url, that was pretty interesting.

**Comment by jakemeltzer333** [comment]
Thanks! Yeah, that was definitely one of the bigger challenges figuring out I could do that. I was definitely stuck for a while and ran into the same error a bunch of times because it kept saying something like 'only absolute urls accepted'. Apparently fetch doesn't like those shortcuts, but because I was already inputting a URL, it worked out well for me!
